username = "yann.degat@numergy.com"
password = "Pass!123456789"
tenant_name = "Numergy-Dev:Deis"
auth_url = "https://cloud.numergy.com/identity/v2.0"
public_key = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC8AsjLK7UPhMJqe1yQXL6lMnMopCRxYaHgsIWaRVx3CLqwvQULGyQ6CPDlVlnwS9aDyEoIPr/7m2zbQn3OiLHWaCihJzF9nWQjG2Wfr5yb+K6Niv+LPBDMkGSpymRR12mAg3ERFA1GzcB1LiVyxP67gfDDRQOXodG4snFTroLoLyJ+pDhgRORk+JjLcBMFWcUGjkxv62jvdqpsWowSLpv3uT9Q+RzlQxFTAezdpJwmGCmBzcLCofFHOjIWsEAu05U2eahkfsKcDdxFeP6XLEBrVnPaXrzw7KsPgRTpUq1wtDdD5HPVeoDvjfNFWtCLay//Nc/lwotolJRH2jIzausT deis"
